const db  = require('./index.js');
const Schemas = require('./Schemas.js');

const sampleProducts = [
  { _id: 1,
    productName: 'The Risk I Took Magnet - Bird - Math - Humor - Animal - Nature - Gift - Stocking Stuffer',
    price: 4.50,
    totalSales: 34173,
    reviews: 5,
    inStock: true,
    creator: 'MincingMockingbird',
    creatorImgUrl: 'https://i.etsystatic.com/iusa/929de3/22170658/iusa_75x75.22170658_8fxe.jpg?version=0',
    quantity: 563,
    handmade: true,
    description: 'What\'s the square root of "Oh, sh-t?" \n\n 2.125" x 3.125" \n\n Metal shell \n\n Mylar/UV protective cover \n\n Flat magnetic back \n\n ©2017 The Mincing Mockingbird™ \n\n mm754ris',
    ready: '1-2 Business Days',
    from: 'United States'},
    { _id: 2,
      productName: 'ututea, it id. Natus facere et a',
      price: 690,
      totalSales: 75846,
      reviews: 1,
      inStock: false,
      creator: 'Della Schiller',
      creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=1',
      quantity: 38487,
      handmade: true,
      description:
       'Ratione autem qui sed eius sit est nulla enim voluptas. Veniam soluta ex molestiae dolores.',
      ready: 'Fri Sep 25 2020 08:02:04 GMT-0500 (Central Daylight Time)',
      from: 'West Sedrick' },
    { _id: 3,
      productName: 'delectus sunt qui, cati. Quod qui odit.',
      price: 10934,
      totalSales: 88180,
      reviews: 2,
      inStock: false,
      creator: 'John Runte',
      creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=2',
      quantity: 39091,
      handmade: true,
      description:
       'Consequatur occaecati consectetur nihil totam. Laboriosam laborum voluptatem.',
      ready: 'Fri Sep 25 2020 08:52:11 GMT-0500 (Central Daylight Time)',
      from: 'Abigaleland' },
    { _id: 4,
      productName: 'omnis ab iste',
      price: 44468,
      totalSales: 81570,
      reviews: 1,
      inStock: false,
      creator: 'Marion Zboncak',
      creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=3',
      quantity: 52841,
      handmade: false,
      description:
       'Voluptate nemo autem consequatur dolor perspiciatis. Quae nulla laudantium ut et totam facere repellat neque. Et aut quis velit maxime. Voluptatum magni autem eum minus. Est aliquam praesentium odio delectus corrupti fuga.',
      ready: 'Fri Sep 25 2020 02:18:57 GMT-0500 (Central Daylight Time)',
      from: 'South Karolann' },
    { _id: 5,
      productName: 'et sed quia',
      price: 56796,
      totalSales: 51776,
      reviews: 2,
      inStock: false,
      creator: 'Kathryn Terry',
      creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=4',
      quantity: 50607,
      handmade: false,
      description:
       'Et veniam optio totam quam et repellendus tenetur fuga magnam. Esse molestias modi nulla ut ab. In culpa repellendus. Dolores eius aspernatur. Dicta et impedit asperiores alias aliquid fugit et. Id esse blanditiis.',
      ready: 'Fri Sep 25 2020 13:41:06 GMT-0500 (Central Daylight Time)',
      from: 'Lake Philip' },
    { _id: 6,
      productName: 'et voluptate architecto',
      price: 80789,
      totalSales: 4522,
      reviews: 0,
      inStock: false,
      creator: 'Bryan Witting',
      creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=5',
      quantity: 44270,
      handmade: false,
      description:
       'Inventore incidunt accusamus sed est. Autem sit vitae praesentium. Voluptatem voluptatem soluta tempora saepe dolorem autem earum sunt velit. Tenetur possimus non ab architecto distinctio sed. Ipsa blanditiis eaque nemo nihil at sapiente quaerat eos.',
      ready: 'Fri Sep 25 2020 06:30:34 GMT-0500 (Central Daylight Time)',
      from: 'Zulaufborough' },
    { _id: 7,
      productName: 'necessitatibus consectetur sapiente',
      price: 9148,
      totalSales: 72539,
      reviews: 0,
      inStock: true,
      creator: 'Heather Barrows',
      creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=6',
      quantity: 76309,
      handmade: false,
      description:
       'Id rem temporibus et molestiae odit qui. Et non quia ex quos quos qui architecto quia ipsa. Accusantium et laudantium. Accusantium quasi suscipit quia aut fugiat tenetur vel. Nostrum sunt et odit aspernatur est minima omnis minima eos. Illum laborum quis corporis aut est non veniam quibusdam sed.',
      ready: 'Fri Sep 25 2020 18:06:22 GMT-0500 (Central Daylight Time)',
      from: 'Lake Darronfurt' },
    { _id: 8,
      productName: 'quia soluta assumenda',
      price: 61564,
      totalSales: 70698,
      reviews: 2,
      inStock: false,
      creator: 'Mrs. Virginia Kreiger',
      creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=7',
      quantity: 38463,
      handmade: true,
      description:
       'Laborum omnis voluptatem molestias quaerat. Quidem ut et totam qui pariatur libero delectus odio est. Cumque deserunt et labore aut perspiciatis officiis quia ipsa. Enim natus dignissimos possimus qui.',
      ready: 'Fri Sep 25 2020 16:29:56 GMT-0500 (Central Daylight Time)',
      from: 'Masonmouth' },
    { _id: 9,
      productName: 'doloremque occaecati ea',
      price: 24015,
      totalSales: 28656,
      reviews: 4,
      inStock: false,
      creator: 'Jay Bogan',
      creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=8',
      quantity: 12322,
      handmade: false,
      description:
       'Distinctio aut quo rem ut officia neque. Doloremque expedita totam qui nemo. Officia modi aliquid fugit temporibus quo in nam qui. Explicabo qui ipsa facilis esse. Voluptatum autem nihil qui rerum blanditiis eveniet est provident.',
      ready: 'Fri Sep 25 2020 19:04:08 GMT-0500 (Central Daylight Time)',
      from: 'East Tayabury' },
    { _id: 10,
      productName: 'iure assumenda voluptates',
      price: 41552,
      totalSales: 40167,
      reviews: 3,
      inStock: true,
      creator: 'Marlon Pollich',
      creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=9',
      quantity: 60201,
      handmade: true,
      description:
       'Voluptas occaecati et est sint. Ipsum impedit quia explicabo quia eveniet et. Non tenetur quia omnis asperiores reprehenderit sed. Explicabo possimus dolor ut placeat aut quia.',
      ready: 'Sat Sep 26 2020 01:02:44 GMT-0500 (Central Daylight Time)',
      from: 'Port Vernastad' },
    { _id: 11,
      productName: 'architecto repudiandae aliquam',
      price: 86164,
      totalSales: 78196,
      reviews: 1,
      inStock: false,
      creator: 'Alice Feeney',
      creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=10',
      quantity: 7990,
      handmade: true,
      description:
       'Cupiditate earum nihil et earum. Iure eveniet aut deleniti non aut perspiciatis omnis possimus. Fugit exercitationem sit qui itaque possimus quis amet. Occaecati tenetur molestias culpa blanditiis aliquid quaerat delectus. Illum at a pariatur magni ut.',
      ready: 'Fri Sep 25 2020 14:57:14 GMT-0500 (Central Daylight Time)',
      from: 'North Eileenfort' },
    { _id: 12,
      productName: 'dolores iusto quas',
      price: 9006,
      totalSales: 52248,
      reviews: 1,
      inStock: false,
      creator: 'Theresa Brakus',
      creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=11',
      quantity: 81899,
      handmade: true,
      description:
       'Incidunt adipisci minus molestias sed rerum in. Facilis labore vero vitae. Sed officiis tempora tenetur. Quisquam et eveniet. Vitae ut facere. Reiciendis adipisci quam commodi eius in eum.',
      ready: 'Fri Sep 25 2020 05:31:31 GMT-0500 (Central Daylight Time)',
      from: 'Funkborough' },
    { _id: 13,
      productName: 'dolor quia rerum',
      price: 52329,
      totalSales: 42498,
      reviews: 4,
      inStock: false,
      creator: 'Katherine Kozey',
      creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=12',
      quantity: 60021,
      handmade: false,
      description: 'Nesciunt minus quae. Voluptatem vel ut.',
      ready: 'Fri Sep 25 2020 13:30:20 GMT-0500 (Central Daylight Time)',
      from: 'Dickihaven' },
    { _id: 14,
      productName: 'facere dolore reprehenderit',
      price: 19402,
      totalSales: 39498,
      reviews: 2,
      inStock: true,
      creator: 'Jimmie Green',
      creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=13',
      quantity: 8938,
      handmade: true,
      description:
       'Facilis architecto omnis sed iste quia quo. Corrupti non assumenda. Unde nisi libero quia. Molestiae quia est aut molestiae aut sed exercitationem facere quo. Quia fugiat est veritatis nisi sit. Sunt officia sunt veniam omnis ut minus temporibus.',
      ready: 'Fri Sep 25 2020 10:27:46 GMT-0500 (Central Daylight Time)',
      from: 'Lubowitzmouth' },
    { _id: 15,
      productName: 'quia harum ea',
      price: 59053,
      totalSales: 20079,
      reviews: 0,
      inStock: true,
      creator: 'Sylvia Homenick',
      creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=14',
      quantity: 17874,
      handmade: false,
      description:
       'Harum sed dicta quae aliquid quis maxime tenetur. Est ratione omnis est aut laborum eveniet dolorum eum et. Amet animi laudantium labore sequi sit eos.',
      ready: 'Fri Sep 25 2020 09:38:39 GMT-0500 (Central Daylight Time)',
      from: 'East Kennedy' },
    { _id: 16,
      productName: 'autem nihil dolorem',
      price: 75632,
      totalSales: 70101,
      reviews: 4,
      inStock: false,
      creator: 'Thomas Keeling',
      creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=15',
      quantity: 51570,
      handmade: true,
      description:
       'Illo illum nam iusto veritatis harum. Quaerat rem eveniet est molestias sunt. Quidem sed rerum sed quibusdam nesciunt ea nihil.',
      ready: 'Fri Sep 25 2020 03:32:56 GMT-0500 (Central Daylight Time)',
      from: 'Lake Jenningsburgh' },
    { _id: 17,
      productName: 'non ea quia',
      price: 41055,
      totalSales: 7397,
      reviews: 4,
      inStock: true,
      creator: 'Amos West',
      creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=16',
      quantity: 24340,
      handmade: false,
      description:
       'Autem voluptatem voluptatum sunt suscipit ratione temporibus rerum laborum. Perferendis aut tempora dolores.',
      ready: 'Fri Sep 25 2020 12:25:16 GMT-0500 (Central Daylight Time)',
      from: 'Jonesport' },
    { _id: 18,
      productName: 'dolor doloribus inventore',
      price: 83954,
      totalSales: 15578,
      reviews: 3,
      inStock: true,
      creator: 'Dr. Lyle Tillman',
      creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=17',
      quantity: 54912,
      handmade: true,
      description:
       'Eaque mollitia iure facere non debitis quidem aperiam consequatur. Laborum neque quo illum quod ut rerum. Sit ratione aperiam beatae. Ratione a dolor velit recusandae et perspiciatis consequatur. Totam reprehenderit mollitia eum reiciendis.',
      ready: 'Fri Sep 25 2020 15:48:00 GMT-0500 (Central Daylight Time)',
      from: 'North Mariannaland' },
    { _id: 19,
      productName: 'voluptatem sit aspernatur',
      price: 70603,
      totalSales: 60109,
      reviews: 5,
      inStock: true,
      creator: 'Laura Hyatt IV',
      creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=18',
      quantity: 95326,
      handmade: false,
      description:
       'Velit dolore inventore facilis commodi omnis excepturi. Ut dolor dignissimos. Similique nihil laudantium quia assumenda id sint commodi maxime itaque. Consectetur perspiciatis asperiores.',
      ready: 'Fri Sep 25 2020 14:14:34 GMT-0500 (Central Daylight Time)',
      from: 'West Catherine' },
    { _id: 20,
      productName: 'perferendis molestias consequatur',
      price: 98662,
      totalSales: 46942,
      reviews: 2,
      inStock: false,
      creator: 'Javier Langworth',
      creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=19',
      quantity: 49617,
      handmade: false,
      description:
       'Enim velit est harum autem quia sapiente ut magnam. Necessitatibus libero id. In inventore aut nihil. Velit voluptas ea eos voluptas.',
      ready: 'Fri Sep 25 2020 06:42:41 GMT-0500 (Central Daylight Time)',
      from: 'South Jedidiah' },
    { _id: 21,
      productName: 'et sequi pariatur',
      price: 8540,
      totalSales: 71298,
      reviews: 1,
      inStock: false,
      creator: 'Kenny Collier',
      creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=20',
      quantity: 70973,
      handmade: false,
      description:
       'Laudantium recusandae ad facere aut et eum sunt itaque nisi. Distinctio veniam tenetur animi sed voluptatem. Voluptas consequatur voluptatem id est sint. Consequatur optio corporis praesentium voluptatem dolorem. Optio sint sunt velit itaque. Autem magnam tenetur quas.',
      ready: 'Fri Sep 25 2020 12:47:38 GMT-0500 (Central Daylight Time)',
      from: 'West Daphney' },
    { _id: 22,
      productName: 'dolor error sunt',
      price: 95417,
      totalSales: 5279,
      reviews: 4,
      inStock: true,
      creator: 'Beth Goldner V',
      creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=21',
      quantity: 81182,
      handmade: false,
      description:
       'Ea ut sunt. Sunt excepturi voluptatem voluptas blanditiis impedit hic molestiae. Vitae fugiat iste eius reiciendis eos ex.',
      ready: 'Fri Sep 25 2020 22:55:49 GMT-0500 (Central Daylight Time)',
      from: 'Port Mauricioborough' },
    { _id: 23,
      productName: 'sed qui nam',
      price: 95513,
      totalSales: 1939,
      reviews: 0,
      inStock: true,
      creator: 'Diana Haag',
      creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=22',
      quantity: 64843,
      handmade: true,
      description:
       'Debitis quis in quas. Nam officia autem asperiores sapiente ullam. Dolorem a vel et veniam. Hic cumque blanditiis non quibusdam vitae occaecati occaecati quidem. In perspiciatis animi vel dolorem veniam minima porro non assumenda.',
      ready: 'Fri Sep 25 2020 23:33:22 GMT-0500 (Central Daylight Time)',
      from: 'New Hyman' },
    { _id: 24,
      productName: 'non doloribus et',
      price: 21527,
      totalSales: 45984,
      reviews: 5,
      inStock: false,
      creator: 'Kristy Okuneva',
      creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=23',
      quantity: 89953,
      handmade: false,
      description:
       'Tempora quam officiis est. Vel vitae suscipit laboriosam porro beatae. Similique et quas qui sint qui dolorem laborum.',
      ready: 'Fri Sep 25 2020 01:19:00 GMT-0500 (Central Daylight Time)',
      from: 'Terryborough' },
    { _id: 25,
      productName: 'eum voluptatem nam',
      price: 4306,
      totalSales: 62720,
      reviews: 1,
      inStock: true,
      creator: 'Mrs. Ebony Toy',
      creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=24',
      quantity: 99606,
      handmade: false,
      description:
       'Similique et ut aperiam officia quidem cum. Iste fugit ut ratione laborum dolores nihil. Dolores sint soluta consequuntur sunt earum voluptas. Nihil vel id aut nemo est. Animi numquam illum vitae cupiditate non.',
      ready: 'Fri Sep 25 2020 16:33:02 GMT-0500 (Central Daylight Time)',
      from: 'Shanahanberg' },
    { _id: 26,
      productName: 'enim vero ad',
      price: 29405,
      totalSales: 17038,
      reviews: 2,
      inStock: true,
      creator: 'May Smitham',
      creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=25',
      quantity: 29908,
      handmade: false,
      description:
       'Debitis dolor quis vitae explicabo corporis. Amet qui iusto aut placeat. Inventore consequatur quisquam eveniet voluptate libero. Et deleniti eveniet repudiandae repellat quo at temporibus accusantium consequatur. Atque rerum ad. Facilis autem aliquam non voluptas qui.',
      ready: 'Fri Sep 25 2020 07:20:58 GMT-0500 (Central Daylight Time)',
      from: 'Andreannehaven' },
    { _id: 27,
      productName: 'alias libero illum',
      price: 29022,
      totalSales: 94558,
      reviews: 1,
      inStock: false,
      creator: 'Rose VonRueden',
      creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=26',
      quantity: 56560,
      handmade: false,
      description:
       'Commodi similique numquam sapiente aspernatur aut quae quidem magnam accusantium. Et corrupti quia dolores voluptatem voluptatem. Aut eveniet porro id in sed voluptate. Dolores eligendi ut autem aliquid nostrum et dolor atque sed.',
      ready: 'Fri Sep 25 2020 03:37:31 GMT-0500 (Central Daylight Time)',
      from: 'North Bradford' },
    { _id: 28,
      productName: 'ipsa voluptas nulla',
      price: 46075,
      totalSales: 53406,
      reviews: 5,
      inStock: true,
      creator: 'Della McKenzie',
      creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=27',
      quantity: 70623,
      handmade: false,
      description:
       'Labore neque est quaerat quia magni modi aut. Libero accusamus magni itaque quia rerum incidunt odio quisquam blanditiis. Quaerat sequi eos nihil impedit.',
      ready: 'Fri Sep 25 2020 19:13:18 GMT-0500 (Central Daylight Time)',
      from: 'McCulloughberg' },
    { _id: 29,
      productName: 'nihil id perspiciatis',
      price: 14750,
      totalSales: 71426,
      reviews: 2,
      inStock: false,
      creator: 'Julius Doyle',
      creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=28',
      quantity: 11958,
      handmade: true,
      description:
       'Sed quod corporis debitis natus vel. Nobis ut harum animi sint quibusdam iste excepturi beatae. Corporis maxime deserunt ullam enim saepe sed maiores.',
      ready: 'Fri Sep 25 2020 03:32:05 GMT-0500 (Central Daylight Time)',
      from: 'East Guy' },
    { _id: 30,
      productName: 'voluptatem sequi rem',
      price: 18648,
      totalSales: 63702,
      reviews: 3,
      inStock: true,
      creator: 'Faye Powlowski V',
      creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=29',
      quantity: 49176,
      handmade: false,
      description:
       'Blanditiis nihil velit maxime saepe accusantium eos. Fugiat quos odio sed. Id doloribus quibusdam. Distinctio possimus voluptatem omnis.',
      ready: 'Fri Sep 25 2020 23:59:07 GMT-0500 (Central Daylight Time)',
      from: 'Margaritahaven' },
    { _id: 31,
      productName: 'eum eligendi distinctio',
      price: 47573,
      totalSales: 35817,
      reviews: 5,
      inStock: false,
      creator: 'Tiffany Hermann',
      creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=30',
      quantity: 7299,
      handmade: false,
      description:
       'Rerum aliquid omnis incidunt vitae et veritatis eligendi. Maxime illum et.',
      ready: 'Fri Sep 25 2020 20:15:33 GMT-0500 (Central Daylight Time)',
      from: 'Concepcionberg' },
    { _id: 32,
      productName: 'perspiciatis occaecati itaque',
      price: 97318,
      totalSales: 76703,
      reviews: 1,
      inStock: false,
      creator: 'Bertha Frami DDS',
      creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=31',
      quantity: 71638,
      handmade: false,
      description:
       'Qui ea non nesciunt odio. Est quo qui fugit optio rerum totam consequuntur deleniti et. Omnis assumenda iste repellendus optio ducimus. Expedita ad aliquid aperiam odio a dolor et consequatur. Sunt nulla animi id quaerat fugiat cupiditate consequatur quis.',
      ready: 'Sat Sep 26 2020 00:36:48 GMT-0500 (Central Daylight Time)',
      from: 'Langfort' },
    { _id: 33,
      productName: 'aspernatur ut rerum',
      price: 34855,
      totalSales: 29978,
      reviews: 1,
      inStock: false,
      creator: 'Mrs. Tamara Rolfson',
      creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=32',
      quantity: 83739,
      handmade: false,
      description:
       'Quasi esse laboriosam a occaecati aut consectetur debitis inventore. Quae inventore ipsam ipsa qui esse hic. Magni hic quia porro iusto architecto necessitatibus.',
      ready: 'Fri Sep 25 2020 20:27:52 GMT-0500 (Central Daylight Time)',
      from: 'East Gordonberg' },
    { _id: 34,
      productName: 'voluptas dolor temporibus',
      price: 38237,
      totalSales: 97975,
      reviews: 5,
      inStock: false,
      creator: 'Todd Ryan',
      creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=33',
      quantity: 95708,
      handmade: true,
      description:
       'Dolore et optio. Odio consequatur aperiam accusantium eos voluptatem et. Unde soluta tenetur. Aut fugit voluptate voluptate alias fugiat quia laboriosam. Accusantium accusamus repudiandae et aliquam cumque. Ipsa ab sunt qui.',
      ready: 'Fri Sep 25 2020 19:32:40 GMT-0500 (Central Daylight Time)',
      from: 'Quigleychester' },
    { _id: 35,
      productName: 'neque molestias et',
      price: 14529,
      totalSales: 57443,
      reviews: 3,
      inStock: true,
      creator: 'Joyce Hermann Sr.',
      creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=34',
      quantity: 74811,
      handmade: true,
      description:
       'Cum laborum eius hic et omnis et culpa sapiente qui. Delectus omnis iste corporis alias voluptate similique molestiae. In officia est consequuntur aut facere velit. Laboriosam animi eius adipisci rerum eveniet qui minima illum.',
      ready: 'Fri Sep 25 2020 17:57:49 GMT-0500 (Central Daylight Time)',
      from: 'New Anya' },
      { _id: 36,
        productName: 'et maiores quos',
        price: 30970,
        totalSales: 94096,
        reviews: 2,
        inStock: true,
        creator: 'Joanna Kihn',
        creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=35',
        quantity: 74361,
        handmade: false,
        description:
         'Est quia recusandae vero quo nemo tempora explicabo vitae. Quas animi laborum minima accusamus ducimus earum sed rerum sed.',
        ready: 'Fri Sep 25 2020 06:00:27 GMT-0500 (Central Daylight Time)',
        from: 'Kassandrabury' },
      { _id: 37,
        productName: 'magni nam error',
        price: 416,
        totalSales: 94420,
        reviews: 5,
        inStock: true,
        creator: 'Rick Corkery',
        creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=36',
        quantity: 18962,
        handmade: false,
        description:
         'Quis possimus illum veniam sed qui. Officiis nam minus dolorem rerum temporibus sed. Fuga sit occaecati modi et eaque minima ipsa voluptas. Numquam nostrum veritatis odio dolorum. Natus qui ut sit.',
        ready: 'Fri Sep 25 2020 05:05:57 GMT-0500 (Central Daylight Time)',
        from: 'Tillmanbury' },
      { _id: 38,
        productName: 'perferendis eos voluptates',
        price: 38455,
        totalSales: 43203,
        reviews: 2,
        inStock: true,
        creator: 'Danielle Satterfield',
        creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=37',
        quantity: 22400,
        handmade: false,
        description:
         'Voluptatem sed facere enim repellat perferendis non. Eum omnis itaque provident voluptatum voluptatem quisquam quidem doloribus. Aut autem odio sunt placeat autem. Eos velit voluptatum qui minima atque voluptas. Sed non in quod. Beatae qui in.',
        ready: 'Fri Sep 25 2020 09:30:07 GMT-0500 (Central Daylight Time)',
        from: 'Grantfort' },
      { _id: 39,
        productName: 'alias recusandae qui',
        price: 26829,
        totalSales: 13712,
        reviews: 3,
        inStock: true,
        creator: 'Greg Wehner',
        creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=38',
        quantity: 64698,
        handmade: true,
        description:
         'Et ex nemo sequi ut maiores velit amet facere dolor. Adipisci quo modi sed dolorum illum quia nemo ut. Numquam molestias officia perspiciatis odit alias. Quibusdam excepturi ea ipsa dolore itaque. Qui atque sit. Quis blanditiis ducimus perferendis sed qui non aperiam.',
        ready: 'Fri Sep 25 2020 17:07:19 GMT-0500 (Central Daylight Time)',
        from: 'Hesselmouth' },
      { _id: 40,
        productName: 'voluptatum et impedit',
        price: 70779,
        totalSales: 89600,
        reviews: 5,
        inStock: true,
        creator: 'Allison Stark',
        creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=39',
        quantity: 29836,
        handmade: false,
        description:
         'Modi dicta omnis inventore ratione nam necessitatibus. Dolor id dolorum accusantium nam qui. Vitae molestias soluta.',
        ready: 'Fri Sep 25 2020 18:43:56 GMT-0500 (Central Daylight Time)',
        from: 'Shanahanfurt' },
      { _id: 41,
        productName: 'sequi aperiam quo',
        price: 80930,
        totalSales: 88278,
        reviews: 3,
        inStock: true,
        creator: 'Krista Morar',
        creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=40',
        quantity: 48604,
        handmade: false,
        description:
         'Et vel autem eum ipsa quaerat magnam. Adipisci maiores qui voluptas eaque odit et. Minus provident animi aut atque porro consequuntur sapiente. Dicta voluptas ducimus aut veniam et et alias.',
        ready: 'Fri Sep 25 2020 08:31:51 GMT-0500 (Central Daylight Time)',
        from: 'North Gunnerport' },
      { _id: 42,
        productName: 'officia quos voluptates',
        price: 55236,
        totalSales: 620,
        reviews: 0,
        inStock: false,
        creator: 'Martin Rau',
        creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=41',
        quantity: 835,
        handmade: false,
        description:
         'Eveniet quam iste mollitia dolores. Veniam impedit harum omnis et quos. Eum veniam ut voluptas numquam modi eius est quam voluptatum. Dolore omnis veniam earum rerum et saepe vel aut.',
        ready: 'Fri Sep 25 2020 02:27:08 GMT-0500 (Central Daylight Time)',
        from: 'Cummeratashire' },
      { _id: 43,
        productName: 'quia dolorem est',
        price: 97906,
        totalSales: 98387,
        reviews: 3,
        inStock: true,
        creator: 'Kimberly Bednar',
        creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=42',
        quantity: 50499,
        handmade: false,
        description:
         'Quo ut sit. Nemo id perspiciatis provident. Porro adipisci et repudiandae temporibus deserunt pariatur omnis magni. Earum est maiores voluptatem eaque voluptate a temporibus voluptas.',
        ready: 'Fri Sep 25 2020 11:52:45 GMT-0500 (Central Daylight Time)',
        from: 'Jonesmouth' },
      { _id: 44,
        productName: 'et consequuntur error',
        price: 20914,
        totalSales: 14907,
        reviews: 4,
        inStock: true,
        creator: 'Dr. Gabriel Champlin',
        creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=43',
        quantity: 41220,
        handmade: false,
        description:
         'Recusandae esse vel provident laudantium ipsum esse. Officiis corrupti sunt voluptatem. Doloribus voluptatem incidunt sunt labore et laudantium. Reprehenderit id harum omnis veritatis occaecati. Repellat nemo tempora et qui mollitia in iure totam. Commodi tempore et voluptatem similique qui asperiores recusandae provident quia.',
        ready: 'Fri Sep 25 2020 12:55:55 GMT-0500 (Central Daylight Time)',
        from: 'Barryview' },
      { _id: 45,
        productName: 'sapiente est quidem',
        price: 41527,
        totalSales: 25784,
        reviews: 3,
        inStock: false,
        creator: 'Alfredo Satterfield',
        creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=44',
        quantity: 63689,
        handmade: true,
        description:
         'Facilis fugiat ipsa nisi beatae minus voluptatibus quibusdam blanditiis. Vel velit est porro non porro est adipisci cumque ut.',
        ready: 'Fri Sep 25 2020 12:53:16 GMT-0500 (Central Daylight Time)',
        from: 'Faheyview' },
      { _id: 46,
        productName: 'fugit ratione quasi',
        price: 68241,
        totalSales: 63455,
        reviews: 1,
        inStock: true,
        creator: 'Beth Olson',
        creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=45',
        quantity: 48126,
        handmade: true,
        description:
         'Ex vel rerum laudantium culpa praesentium et. Sapiente nihil facilis eos ut fugit id quo. Omnis voluptates ut dolores quis minima voluptatum ipsam odio libero. Vero nemo exercitationem fugiat sed cum. Voluptate ducimus reprehenderit. Commodi eum corrupti modi accusamus cumque harum.',
        ready: 'Fri Sep 25 2020 23:01:55 GMT-0500 (Central Daylight Time)',
        from: 'Mekhitown' },
      { _id: 47,
        productName: 'facere facere molestiae',
        price: 26833,
        totalSales: 43848,
        reviews: 4,
        inStock: true,
        creator: 'Ramon Feest',
        creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=46',
        quantity: 99257,
        handmade: false,
        description:
         'Et ipsa velit quos. Fugiat doloremque dolor cupiditate. Earum et animi porro et. Temporibus sed velit quis quia autem sed ut blanditiis. Dolorem soluta soluta quae. Consequuntur reiciendis consequuntur dolor autem voluptatem est qui.',
        ready: 'Fri Sep 25 2020 21:11:44 GMT-0500 (Central Daylight Time)',
        from: 'East Jaclynview' },
      { _id: 48,
        productName: 'praesentium nihil in',
        price: 73355,
        totalSales: 37685,
        reviews: 5,
        inStock: true,
        creator: 'Yvonne Hauck II',
        creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=47',
        quantity: 19322,
        handmade: false,
        description:
         'Ut dolor consequatur optio ut. Aperiam ex aut a cupiditate officiis ut. Tenetur et sint sequi. Amet optio accusantium adipisci ad. Nam esse commodi.',
        ready: 'Fri Sep 25 2020 11:47:33 GMT-0500 (Central Daylight Time)',
        from: 'South Cyril' },
      { _id: 49,
        productName: 'sapiente consequatur quis',
        price: 17207,
        totalSales: 19311,
        reviews: 2,
        inStock: true,
        creator: 'Clyde Osinski',
        creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=48',
        quantity: 10045,
        handmade: true,
        description:
         'Fuga qui minus odit quae. Quia consequatur voluptatem ipsum recusandae odit exercitationem nisi qui saepe. Dolores dolores dolor facilis nostrum ipsa laboriosam odit dolores nobis. Harum temporibus odit sint quibusdam.',
        ready: 'Fri Sep 25 2020 12:32:02 GMT-0500 (Central Daylight Time)',
        from: 'West Normastad' },
      { _id: 50,
        productName: 'voluptates qui vitae',
        price: 73045,
        totalSales: 61214,
        reviews: 0,
        inStock: true,
        creator: 'Dr. Everett Denesik',
        creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=49',
        quantity: 39911,
        handmade: false,
        description:
         'Et iure expedita voluptatem ipsam rem. Est laborum perspiciatis sit inventore et. Ea aliquam at consequuntur dolorum. Quae qui est consequuntur ab et dicta nam totam consequuntur. Optio et voluptatem eaque. Harum quisquam dolore omnis corrupti.',
        ready: 'Sat Sep 26 2020 00:41:12 GMT-0500 (Central Daylight Time)',
        from: 'Sporerland' },
      { _id: 51,
        productName: 'expedita accusamus doloremque',
        price: 35077,
        totalSales: 82598,
        reviews: 3,
        inStock: false,
        creator: 'Miss Dianna Sipes',
        creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=50',
        quantity: 27082,
        handmade: true,
        description:
         'Est nobis ad quisquam cumque consequatur fugit. Quam est rerum quo modi saepe aut ut perspiciatis. Itaque non omnis consequuntur voluptatem mollitia rem iusto eveniet sint. Repellendus officia quas.',
        ready: 'Fri Sep 25 2020 21:53:43 GMT-0500 (Central Daylight Time)',
        from: 'South Shaniyaborough' },
      { _id: 52,
        productName: 'voluptas explicabo minus',
        price: 575,
        totalSales: 88134,
        reviews: 4,
        inStock: true,
        creator: 'Doug Schoen',
        creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=51',
        quantity: 54395,
        handmade: false,
        description:
         'Non error perferendis. Perferendis expedita inventore provident ipsam libero consequuntur modi rerum quod. Neque incidunt accusamus.',
        ready: 'Fri Sep 25 2020 16:43:19 GMT-0500 (Central Daylight Time)',
        from: 'New Oswald' },
      { _id: 53,
        productName: 'et aut in',
        price: 46891,
        totalSales: 16643,
        reviews: 4,
        inStock: false,
        creator: 'Arthur Weimann',
        creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=52',
        quantity: 81246,
        handmade: true,
        description:
         'Dolorum qui dolorem. Aperiam quod officiis sed dolores. Minima veniam officiis delectus assumenda dolores et aut. Ipsum neque veniam ut in minima recusandae veniam qui. Et optio dolor deleniti repellat blanditiis animi. Repellat nam harum id id minima dolor quo in.',
        ready: 'Fri Sep 25 2020 17:08:29 GMT-0500 (Central Daylight Time)',
        from: 'New Matildefort' },
      { _id: 54,
        productName: 'tenetur beatae in',
        price: 75306,
        totalSales: 88761,
        reviews: 5,
        inStock: false,
        creator: 'Wilfred Huels II',
        creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=53',
        quantity: 86795,
        handmade: false,
        description:
         'Corrupti ut eum temporibus dolor nulla. Ea quia repellendus quis velit veniam esse ullam.',
        ready: 'Fri Sep 25 2020 09:52:34 GMT-0500 (Central Daylight Time)',
        from: 'New Marcus' },
      { _id: 55,
        productName: 'quis sapiente veritatis',
        price: 71283,
        totalSales: 71088,
        reviews: 5,
        inStock: false,
        creator: 'Bryant Moen',
        creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=54',
        quantity: 85563,
        handmade: false,
        description: 'Facilis quibusdam aliquid facere. Eum autem non.',
        ready: 'Fri Sep 25 2020 08:32:01 GMT-0500 (Central Daylight Time)',
        from: 'North Katelynbury' },
      { _id: 56,
        productName: 'quis id consequatur',
        price: 20142,
        totalSales: 27444,
        reviews: 5,
        inStock: false,
        creator: 'Harriet Kuhlman',
        creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=55',
        quantity: 80152,
        handmade: true,
        description:
         'Voluptatem ea repellendus non non. Dolorem ut ipsum debitis vitae tempore animi laboriosam aliquid.',
        ready: 'Fri Sep 25 2020 23:46:38 GMT-0500 (Central Daylight Time)',
        from: 'North Myrlshire' },
      { _id: 57,
        productName: 'recusandae a est',
        price: 22915,
        totalSales: 20699,
        reviews: 3,
        inStock: false,
        creator: 'Alexander Ziemann',
        creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=56',
        quantity: 3018,
        handmade: false,
        description:
         'Sit et cum et sit nisi. Rerum in ad corporis repudiandae harum provident voluptas aut ut. Cumque sit excepturi quia mollitia eum maxime pariatur. Ut eligendi iusto aut sint sint unde dolore. Qui rem earum et natus et voluptas qui et. Qui repellat eos eum.',
        ready: 'Fri Sep 25 2020 10:22:53 GMT-0500 (Central Daylight Time)',
        from: 'South Bonnie' },
      { _id: 58,
        productName: 'et sunt et',
        price: 78245,
        totalSales: 38598,
        reviews: 3,
        inStock: false,
        creator: 'Rafael Funk',
        creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=57',
        quantity: 9604,
        handmade: true,
        description:
         'Similique culpa molestiae dolores rerum in mollitia. Sed sit nostrum.',
        ready: 'Fri Sep 25 2020 02:01:47 GMT-0500 (Central Daylight Time)',
        from: 'Eastonchester' },
      { _id: 59,
        productName: 'a deleniti enim',
        price: 54266,
        totalSales: 77518,
        reviews: 0,
        inStock: true,
        creator: 'Dr. Keith Gaylord',
        creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=58',
        quantity: 98430,
        handmade: false,
        description:
         'Dolorem repudiandae et. Accusamus ex occaecati et itaque nesciunt debitis veritatis at omnis. Et delectus sed omnis minus voluptates ad ipsa nihil sed.',
        ready: 'Sat Sep 26 2020 00:05:04 GMT-0500 (Central Daylight Time)',
        from: 'Lake Arthur' },
      { _id: 60,
        productName: 'harum in aspernatur',
        price: 22392,
        totalSales: 91315,
        reviews: 3,
        inStock: true,
        creator: 'Salvador Leffler',
        creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=59',
        quantity: 10386,
        handmade: false,
        description:
         'Dignissimos soluta a animi culpa alias voluptas qui rem rem. Ad excepturi corrupti minima est.',
        ready: 'Fri Sep 25 2020 03:16:19 GMT-0500 (Central Daylight Time)',
        from: 'Ullrichtown' },
      { _id: 61,
        productName: 'non incidunt occaecati',
        price: 60682,
        totalSales: 99403,
        reviews: 5,
        inStock: false,
        creator: 'Sandra Pagac',
        creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=60',
        quantity: 33971,
        handmade: true,
        description:
         'Qui reprehenderit omnis et minus porro voluptate. Harum consectetur quod mollitia voluptatem.',
        ready: 'Fri Sep 25 2020 17:49:53 GMT-0500 (Central Daylight Time)',
        from: 'VonRuedenhaven' },
      { _id: 62,
        productName: 'facere porro non',
        price: 48395,
        totalSales: 90911,
        reviews: 2,
        inStock: true,
        creator: 'Tomas Keeling',
        creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=61',
        quantity: 89768,
        handmade: true,
        description:
         'Molestiae velit qui. Recusandae est tempora veniam. Qui vitae veritatis labore alias distinctio. Necessitatibus porro ut. Expedita aut est aut eum nihil aliquid est culpa perferendis.',
        ready: 'Fri Sep 25 2020 21:08:54 GMT-0500 (Central Daylight Time)',
        from: 'Lake Jeffryport' },
      { _id: 63,
        productName: 'maiores tenetur repudiandae',
        price: 77928,
        totalSales: 79736,
        reviews: 4,
        inStock: true,
        creator: 'Joseph Hagenes',
        creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=62',
        quantity: 26294,
        handmade: false,
        description:
         'Sed velit fugiat. Dolores aliquid distinctio vero est. Adipisci nemo rerum. Aut suscipit et tempora cum porro impedit molestias qui nesciunt. Assumenda perferendis blanditiis. Iusto voluptas id molestias quo error est.',
        ready: 'Fri Sep 25 2020 16:21:15 GMT-0500 (Central Daylight Time)',
        from: 'Novellaville' },
      { _id: 64,
        productName: 'et laborum quam',
        price: 86476,
        totalSales: 17323,
        reviews: 2,
        inStock: true,
        creator: 'Van Treutel',
        creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=63',
        quantity: 65498,
        handmade: false,
        description:
         'Quasi consequatur cumque. Nesciunt est vel asperiores dolor voluptas dolore omnis dicta similique. Minima aut et modi odio eius eligendi deleniti voluptatibus omnis. Quis rem et eum sequi numquam est sunt.',
        ready: 'Fri Sep 25 2020 23:08:02 GMT-0500 (Central Daylight Time)',
        from: 'Jacksonville' },
      { _id: 65,
        productName: 'ut qui enim',
        price: 34939,
        totalSales: 3823,
        reviews: 1,
        inStock: false,
        creator: 'Ross Schultz',
        creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=64',
        quantity: 30303,
        handmade: true,
        description:
         'Voluptatem ut enim maiores reprehenderit veritatis consequatur maiores aut unde. Perferendis minus occaecati quia nostrum nemo consectetur. Saepe reiciendis recusandae officia perferendis hic sit.',
        ready: 'Fri Sep 25 2020 18:06:31 GMT-0500 (Central Daylight Time)',
        from: 'East Estel' },
      { _id: 66,
        productName: 'accusantium et consequatur',
        price: 61555,
        totalSales: 45495,
        reviews: 3,
        inStock: true,
        creator: 'Jenna Aufderhar',
        creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=65',
        quantity: 67245,
        handmade: true,
        description:
         'Quasi veniam vel. Est voluptate deleniti enim ut commodi est delectus nobis. Quibusdam id qui ad porro laboriosam molestiae mollitia. Ducimus id eius nisi. Laborum possimus aut labore.',
        ready: 'Fri Sep 25 2020 11:01:33 GMT-0500 (Central Daylight Time)',
        from: 'Demondberg' },
      { _id: 67,
        productName: 'earum repellat animi',
        price: 54957,
        totalSales: 97421,
        reviews: 3,
        inStock: true,
        creator: 'Darrell Kuhic',
        creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=66',
        quantity: 3841,
        handmade: false,
        description:
         'Praesentium qui voluptatem facere autem optio voluptatem quasi aut. Doloremque architecto velit unde laborum aliquid molestiae error. Quis autem aspernatur pariatur adipisci eos inventore facilis consequuntur. Nobis facilis ad quaerat. Mollitia velit ullam.',
        ready: 'Fri Sep 25 2020 23:14:52 GMT-0500 (Central Daylight Time)',
        from: 'North Beulahhaven' },
      { _id: 68,
        productName: 'omnis unde neque',
        price: 37575,
        totalSales: 15715,
        reviews: 4,
        inStock: true,
        creator: 'Shelley Miller',
        creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=67',
        quantity: 32180,
        handmade: true,
        description:
         'Ullam dignissimos sed blanditiis quibusdam repellendus nulla nihil odit vitae. Atque aut omnis ipsam dolor aspernatur saepe sit rerum voluptatum.',
        ready: 'Fri Sep 25 2020 15:05:58 GMT-0500 (Central Daylight Time)',
        from: 'Lake Schuylerton' },
      { _id: 69,
        productName: 'id ipsa est',
        price: 56787,
        totalSales: 15543,
        reviews: 2,
        inStock: false,
        creator: 'Wilbur Harris',
        creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=68',
        quantity: 19788,
        handmade: false,
        description:
         'Beatae est accusantium repellendus quia consequuntur voluptates facere occaecati eum. At adipisci voluptas sunt unde id magnam architecto minus.',
        ready: 'Fri Sep 25 2020 21:34:24 GMT-0500 (Central Daylight Time)',
        from: 'Sabrynaview' },
        { _id: 70,
          productName: 'est ut et',
          price: 72543,
          totalSales: 76612,
          reviews: 1,
          inStock: true,
          creator: 'Charles Monahan',
          creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=69',
          quantity: 73429,
          handmade: true,
          description:
           'Mollitia omnis eaque neque nihil tenetur. Ut dolore repudiandae laborum qui repellat. Ullam sit quisquam eligendi dolores. Assumenda at eos quia. Cupiditate ratione rerum atque. Cupiditate omnis velit quas repellat consequatur ipsum.',
          ready: 'Fri Sep 25 2020 22:27:13 GMT-0500 (Central Daylight Time)',
          from: 'Port Jazmyn' },
        { _id: 71,
          productName: 'amet ratione et',
          price: 77426,
          totalSales: 30497,
          reviews: 1,
          inStock: true,
          creator: 'Irma Gislason',
          creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=70',
          quantity: 7676,
          handmade: false,
          description:
           'Assumenda nisi enim consequatur ut ratione quia magni. Aut quo voluptas molestias aut dolor id sit repudiandae vel.',
          ready: 'Fri Sep 25 2020 06:31:16 GMT-0500 (Central Daylight Time)',
          from: 'Gleichnermouth' },
        { _id: 72,
          productName: 'ex eaque fuga',
          price: 23158,
          totalSales: 76867,
          reviews: 3,
          inStock: false,
          creator: 'Dr. Jermaine Moore',
          creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=71',
          quantity: 10801,
          handmade: false,
          description:
           'Qui tempora molestiae recusandae delectus quas. Ut qui est sunt aut consequatur sed ea. A et nulla fugiat et ut maiores.',
          ready: 'Fri Sep 25 2020 10:19:04 GMT-0500 (Central Daylight Time)',
          from: 'Malachitown' },
        { _id: 73,
          productName: 'expedita ipsa amet',
          price: 6356,
          totalSales: 49061,
          reviews: 0,
          inStock: true,
          creator: 'Noah Graham',
          creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=72',
          quantity: 56640,
          handmade: true,
          description:
           'Voluptatem sint rerum id. Harum et nostrum earum. Nemo cum qui sit iusto pariatur.',
          ready: 'Fri Sep 25 2020 06:05:51 GMT-0500 (Central Daylight Time)',
          from: 'Port Charleyfort' },
        { _id: 74,
          productName: 'alias et labore',
          price: 84592,
          totalSales: 25411,
          reviews: 1,
          inStock: true,
          creator: 'Toni Huels',
          creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=73',
          quantity: 47392,
          handmade: true,
          description:
           'Dolores nesciunt placeat. Veritatis culpa architecto sed et. Asperiores a enim laudantium et aut. Vel veniam iste eius.',
          ready: 'Fri Sep 25 2020 16:47:51 GMT-0500 (Central Daylight Time)',
          from: 'Lake Marisolton' },
        { _id: 75,
          productName: 'sed dignissimos nobis',
          price: 92657,
          totalSales: 69998,
          reviews: 5,
          inStock: false,
          creator: 'Eric Ferry',
          creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=74',
          quantity: 74803,
          handmade: true,
          description:
           'Velit dolores accusamus dignissimos ratione commodi ipsum sint facere. Accusamus in vero quo. Ex possimus vel maxime dicta fugiat debitis aliquam alias temporibus. Quasi qui sed sint excepturi quidem. Tenetur blanditiis eos.',
          ready: 'Fri Sep 25 2020 15:08:18 GMT-0500 (Central Daylight Time)',
          from: 'East Carmeloberg' },
        { _id: 76,
          productName: 'fugiat illum ut',
          price: 41545,
          totalSales: 52989,
          reviews: 1,
          inStock: true,
          creator: 'Adrienne Kautzer',
          creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=75',
          quantity: 26135,
          handmade: false,
          description:
           'Pariatur cum sunt delectus rerum iste. Illum ut perspiciatis voluptate sequi impedit aut. Sint expedita perspiciatis quasi earum quis in nihil harum. Eveniet eius aut.',
          ready: 'Fri Sep 25 2020 09:43:23 GMT-0500 (Central Daylight Time)',
          from: 'Adolfoland' },
        { _id: 77,
          productName: 'molestiae a architecto',
          price: 46810,
          totalSales: 12714,
          reviews: 1,
          inStock: false,
          creator: 'Dennis Roberts',
          creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=76',
          quantity: 16686,
          handmade: true,
          description:
           'Aut maxime quam ducimus sit sunt ut pariatur eum fugit. Voluptatum aut magni similique occaecati dolores tenetur quo sapiente. Quo deleniti dolores architecto. Minima sed cupiditate quidem fuga tempora earum qui fugiat. Dolor hic sunt sit necessitatibus et voluptate temporibus laudantium.',
          ready: 'Fri Sep 25 2020 19:17:48 GMT-0500 (Central Daylight Time)',
          from: 'Lake Eldahaven' },
        { _id: 78,
          productName: 'voluptatibus expedita quia',
          price: 17337,
          totalSales: 46578,
          reviews: 2,
          inStock: true,
          creator: 'Damon Dietrich',
          creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=77',
          quantity: 74359,
          handmade: true,
          description:
           'Aut velit nulla qui nemo voluptatem. Sit aut provident architecto aperiam. Aut iste cum repellendus officia laboriosam commodi alias. Ratione ut molestias.',
          ready: 'Fri Sep 25 2020 23:31:18 GMT-0500 (Central Daylight Time)',
          from: 'North Adalbertoland' },
        { _id: 79,
          productName: 'vitae nobis veniam',
          price: 62124,
          totalSales: 79598,
          reviews: 3,
          inStock: true,
          creator: 'Christy Wintheiser II',
          creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=78',
          quantity: 42918,
          handmade: true,
          description:
           'Eveniet amet et sed sunt. Maiores quam adipisci enim veritatis dolor est aspernatur velit et. Eos id modi quo non. Dolor dolores deleniti aut qui repellat quasi qui et est. Est iste occaecati.',
          ready: 'Fri Sep 25 2020 06:50:35 GMT-0500 (Central Daylight Time)',
          from: 'Maryamberg' },
        { _id: 80,
          productName: 'numquam voluptatum enim',
          price: 4658,
          totalSales: 35971,
          reviews: 0,
          inStock: true,
          creator: 'Lynne Schamberger',
          creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=79',
          quantity: 68806,
          handmade: false,
          description:
           'Fuga ut quisquam consequatur qui rerum quod reiciendis. Ut repellendus sed sunt similique.',
          ready: 'Sat Sep 26 2020 00:04:12 GMT-0500 (Central Daylight Time)',
          from: 'New Jennie' },
        { _id: 81,
          productName: 'quia facilis libero',
          price: 37311,
          totalSales: 55397,
          reviews: 5,
          inStock: true,
          creator: 'Clifford Klein',
          creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=80',
          quantity: 49526,
          handmade: true,
          description:
           'Velit nihil voluptates a distinctio quod ullam. Molestias quo quisquam possimus ad ad. Quia quod delectus rerum ex exercitationem ipsa. Debitis facere laboriosam porro.',
          ready: 'Fri Sep 25 2020 05:59:01 GMT-0500 (Central Daylight Time)',
          from: 'Hilllchester' },
        { _id: 82,
          productName: 'cum accusantium aspernatur',
          price: 3641,
          totalSales: 13523,
          reviews: 3,
          inStock: false,
          creator: 'Jo Russel',
          creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=81',
          quantity: 81053,
          handmade: true,
          description:
           'Beatae totam libero qui eos esse. Deleniti facere reprehenderit quam repellat qui reiciendis. Rerum maiores reiciendis eos provident modi sit et voluptas. Repellendus voluptates laborum tempora id et architecto molestias.',
          ready: 'Fri Sep 25 2020 21:23:40 GMT-0500 (Central Daylight Time)',
          from: 'West Nathanaelland' },
        { _id: 83,
          productName: 'iusto pariatur ratione',
          price: 16118,
          totalSales: 17640,
          reviews: 4,
          inStock: false,
          creator: 'Arthur Glover',
          creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=82',
          quantity: 98493,
          handmade: true,
          description:
           'Architecto vitae delectus ullam blanditiis necessitatibus. Facere facilis accusamus dolor tempore rerum dolor est. Enim voluptatem dolorem tenetur aut sunt iste provident omnis.',
          ready: 'Fri Sep 25 2020 01:29:31 GMT-0500 (Central Daylight Time)',
          from: 'North Ulises' },
        { _id: 84,
          productName: 'quia quas magni',
          price: 37447,
          totalSales: 92739,
          reviews: 1,
          inStock: false,
          creator: 'Carl Bode',
          creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=83',
          quantity: 77788,
          handmade: false,
          description:
           'Quo eveniet dolores. Qui odio voluptas est quidem quia eveniet necessitatibus aspernatur dolores. Quia exercitationem laboriosam voluptatem voluptate libero culpa ut quis. Animi sed facere qui accusantium commodi consequatur dolor sapiente. Est ipsum occaecati sequi ut.',
          ready: 'Fri Sep 25 2020 17:11:26 GMT-0500 (Central Daylight Time)',
          from: 'Klingmouth' },
        { _id: 85,
          productName: 'et veritatis sapiente',
          price: 99102,
          totalSales: 78714,
          reviews: 2,
          inStock: true,
          creator: 'Wilbur Ruecker PhD',
          creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=84',
          quantity: 12726,
          handmade: true,
          description:
           'Ut nihil ullam cumque qui cum aut iste quis. Dolorem odio et aperiam nostrum ipsam quam. Ut itaque nemo fugiat adipisci. Fugiat aut ea quis labore quos mollitia qui aliquid accusantium.',
          ready: 'Fri Sep 25 2020 08:55:27 GMT-0500 (Central Daylight Time)',
          from: 'South Wellingtonstad' },
        { _id: 86,
          productName: 'ut at illum',
          price: 6387,
          totalSales: 43481,
          reviews: 5,
          inStock: false,
          creator: 'Gertrude Kutch',
          creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=85',
          quantity: 15873,
          handmade: true,
          description:
           'Blanditiis excepturi deleniti earum repellat qui ab dolorem. Deleniti illum eveniet quas non ut dolore enim aperiam esse. Reiciendis sunt nulla. Aut qui omnis pariatur provident. Suscipit sint ratione possimus voluptas.',
          ready: 'Fri Sep 25 2020 17:21:46 GMT-0500 (Central Daylight Time)',
          from: 'Port Reece' },
        { _id: 87,
          productName: 'a sequi dolore',
          price: 54055,
          totalSales: 71558,
          reviews: 3,
          inStock: false,
          creator: 'Lori Buckridge',
          creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=86',
          quantity: 31662,
          handmade: true,
          description:
           'Provident voluptatum recusandae. Totam ut doloremque est ea eum quo sapiente ad expedita. Porro repellendus cupiditate deleniti dolores aperiam dolore pariatur consequatur totam. Corporis quod aliquid ut ad tempora.',
          ready: 'Fri Sep 25 2020 09:35:01 GMT-0500 (Central Daylight Time)',
          from: 'Tremblayville' },
        { _id: 88,
          productName: 'dolorum nihil qui',
          price: 31703,
          totalSales: 98388,
          reviews: 4,
          inStock: true,
          creator: 'Kurt White',
          creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=87',
          quantity: 60959,
          handmade: false,
          description:
           'Quia aut et blanditiis. In voluptates debitis aliquam expedita voluptatem ut quo.',
          ready: 'Fri Sep 25 2020 05:52:41 GMT-0500 (Central Daylight Time)',
          from: 'West Mosesshire' },
        { _id: 89,
          productName: 'quod harum vel',
          price: 4661,
          totalSales: 43647,
          reviews: 1,
          inStock: true,
          creator: 'Rose Funk',
          creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=88',
          quantity: 94811,
          handmade: true,
          description:
           'Modi provident vero laudantium ut sint vel eveniet cupiditate. Sint et suscipit aut voluptates eveniet.',
          ready: 'Fri Sep 25 2020 13:29:49 GMT-0500 (Central Daylight Time)',
          from: 'Pipertown' },
        { _id: 90,
          productName: 'sed quo omnis',
          price: 76113,
          totalSales: 29515,
          reviews: 2,
          inStock: false,
          creator: 'Miss Sonja West',
          creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=89',
          quantity: 87160,
          handmade: false,
          description:
           'Libero impedit saepe quaerat iure cum. Praesentium sequi vel atque error vitae placeat maxime. Repudiandae laudantium quo omnis sed omnis. Nobis vel vel necessitatibus et voluptatibus quisquam eum minima. Suscipit veritatis voluptate incidunt.',
          ready: 'Fri Sep 25 2020 14:49:59 GMT-0500 (Central Daylight Time)',
          from: 'New Flaviotown' },
        { _id: 91,
          productName: 'aut nisi quae',
          price: 64798,
          totalSales: 40991,
          reviews: 3,
          inStock: true,
          creator: 'Simon Herman',
          creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=90',
          quantity: 98320,
          handmade: false,
          description:
           'Harum architecto ipsam magnam. Magnam nam ipsa. Labore sit explicabo minus nihil ducimus et adipisci. Excepturi a cumque qui provident maxime non excepturi et consectetur. Qui fuga et vel quisquam quod voluptates.',
          ready: 'Fri Sep 25 2020 03:07:55 GMT-0500 (Central Daylight Time)',
          from: 'Lake Lilyville' },
        { _id: 92,
          productName: 'dolores eius delectus',
          price: 71851,
          totalSales: 84093,
          reviews: 1,
          inStock: true,
          creator: 'Francis Breitenberg',
          creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=91',
          quantity: 58460,
          handmade: true,
          description:
           'Magnam quidem dolor. Debitis repudiandae et assumenda illo tenetur ut iure. Blanditiis reiciendis quia blanditiis voluptas ut aut. Consequuntur ut amet dolor architecto rerum molestiae. Qui sed occaecati explicabo vel quia explicabo debitis omnis harum.',
          ready: 'Fri Sep 25 2020 02:40:14 GMT-0500 (Central Daylight Time)',
          from: 'East Caterina' },
        { _id: 93,
          productName: 'optio quia aut',
          price: 53315,
          totalSales: 73663,
          reviews: 4,
          inStock: true,
          creator: 'Justin Daugherty',
          creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=92',
          quantity: 24547,
          handmade: false,
          description:
           'Praesentium corporis ducimus. Quia et amet ea. Consequatur explicabo quia saepe autem sed veritatis sit. Pariatur in qui officia fuga quas doloremque numquam voluptatem. Ut quibusdam qui deserunt quia impedit accusamus. Est nesciunt est enim nemo placeat et.',
          ready: 'Sat Sep 26 2020 01:16:21 GMT-0500 (Central Daylight Time)',
          from: 'South Gussieshire' },
        { _id: 94,
          productName: 'eveniet et nulla',
          price: 91685,
          totalSales: 70145,
          reviews: 2,
          inStock: false,
          creator: 'Paul Rutherford II',
          creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=93',
          quantity: 67756,
          handmade: true,
          description:
           'Dolorum laborum totam id maxime dolorem. Quis necessitatibus vel libero reprehenderit sint vel eos laboriosam nisi. Eum dolor ipsa quam ut aut tenetur fuga. Rem et dicta velit aperiam eaque modi laudantium et. Voluptas dignissimos illo omnis ut reiciendis aliquam est dolorum.',
          ready: 'Fri Sep 25 2020 06:35:17 GMT-0500 (Central Daylight Time)',
          from: 'Bergstromfurt' },
        { _id: 95,
          productName: 'non totam est',
          price: 78656,
          totalSales: 98708,
          reviews: 0,
          inStock: false,
          creator: 'Rosa Kihn',
          creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=94',
          quantity: 8543,
          handmade: false,
          description:
           'Ut quod recusandae sed enim minima quo facilis eos sint. Sint qui eaque. Quis omnis et temporibus voluptate autem quia deleniti. Minima facilis ratione ut asperiores sapiente aspernatur dolorem molestias veniam.',
          ready: 'Fri Sep 25 2020 15:38:43 GMT-0500 (Central Daylight Time)',
          from: 'New Cobyland' },
        { _id: 96,
          productName: 'quia voluptatem voluptatem',
          price: 25053,
          totalSales: 84428,
          reviews: 1,
          inStock: false,
          creator: 'Gregg Kris',
          creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=95',
          quantity: 20408,
          handmade: false,
          description:
           'Non et iste iure. Consequatur dolores eos possimus. Consequuntur voluptatem eligendi.',
          ready: 'Fri Sep 25 2020 17:32:53 GMT-0500 (Central Daylight Time)',
          from: 'North Madonna' },
        { _id: 97,
          productName: 'eum beatae est',
          price: 25726,
          totalSales: 21673,
          reviews: 4,
          inStock: true,
          creator: 'Crystal Walter',
          creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=96',
          quantity: 21769,
          handmade: false,
          description:
           'Necessitatibus repellat totam vel. Laudantium atque explicabo ipsa commodi ipsam. Adipisci iusto suscipit quod ut quo. Omnis et praesentium ut explicabo quisquam. Modi delectus itaque qui saepe et aut eum.',
          ready: 'Fri Sep 25 2020 23:15:56 GMT-0500 (Central Daylight Time)',
          from: 'Lake Sydnee' },
        { _id: 98,
          productName: 'asperiores inventore ut',
          price: 72661,
          totalSales: 84867,
          reviews: 1,
          inStock: false,
          creator: 'Mabel Wolff DDS',
          creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=97',
          quantity: 13179,
          handmade: false,
          description:
           'Culpa explicabo dolore sit eum sunt consequatur a enim. Itaque ut nulla aut porro eum ad suscipit dignissimos. Vero repudiandae molestias vero vitae quo tempore aut.',
          ready: 'Sat Sep 26 2020 00:17:02 GMT-0500 (Central Daylight Time)',
          from: 'Lake Gisselleshire' },
        { _id: 99,
          productName: 'ab soluta rerum',
          price: 3046,
          totalSales: 31638,
          reviews: 1,
          inStock: false,
          creator: 'Mr. Jose Goyette',
          creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=98',
          quantity: 23063,
          handmade: false,
          description:
           'Voluptatibus aperiam nam et. Quasi accusantium excepturi autem omnis qui et consequatur.',
          ready: 'Fri Sep 25 2020 13:46:40 GMT-0500 (Central Daylight Time)',
          from: 'Mayerstad' },
        { _id: 100,
          productName: 'officia nostrum quis',
          price: 80527,
          totalSales: 25224,
          reviews: 4,
          inStock: false,
          creator: 'Cheryl Torphy DDS',
          creatorImgUrl: 'https://source.unsplash.com/random/200x200?sig=99',
          quantity: 60604,
          handmade: false,
          description:
           'Iusto ut aut dignissimos hic atque non unde. Asperiores assumenda a autem vel nemo natus et ut. Iusto similique qui voluptas dolor quia perspiciatis et modi quia. Dolorem aut adipisci suscipit facilis. Beatae nesciunt harum praesentium aut.',
          ready: 'Fri Sep 25 2020 06:47:36 GMT-0500 (Central Daylight Time)',
          from: 'East Daisytown' }
];


//<--------------------------------------------------------------------->

const sampleShippingData = [
  {
    _id: 1,
    ready: '1-2 business days',
    from: 'United States',
    to: 'Australia',
    zipCode: 123456,
    cost: 14,
  },
  {
    _id: 2,
    ready: '2-3 business days',
    from: 'United States',
    to: 'Canada',
    zipCode: 123456,
    cost: 16,
  },
  {
    _id: 3,
    ready: '4 business days',
    from: 'United States',
    to: 'France',
    zipCode: 123456,
    cost: 18,
  },
  {
    _id: 4,
    ready: '1 business days',
    from: 'United States',
    to: 'Germany',
    zipCode: 123456,
    cost: 20,
  },
  {
    _id: 5,
    ready: '5 business days',
    from: 'United States',
    to: 'Greece',
    zipCode: 123456,
    cost: 22,
  },
  {
    _id: 6,
    ready: '3 business days',
    from: 'United States',
    to: 'Australia',
    zipCode: 654321,
    cost: 15,
  },
  {
    _id: 7,
    ready: '4 business days',
    from: 'United States',
    to: 'Canada',
    zipCode: 654321,
    cost: 17,
  },
  {
    _id: 8,
    ready: '6 business days',
    from: 'United States',
    to: 'France',
    zipCode: 654321,
    cost: 19,
  },
  {
    _id: 9,
    ready: '10 business days',
    from: 'United States',
    to: 'Germany',
    zipCode: 654321,
    cost: 21,
  },
  {
    _id: 10,
    ready: '11 business days',
    from: 'United States',
    to: 'Greece',
    zipCode: 654321,
    cost: 23,
  }
]

//<--------------------------------------------------------------------->

const insertSampleProducts = function() {
  Schemas.Product.create(sampleProducts)
    .then(() => db.disconnect());
};

insertSampleProducts();

const insertSampleShippingData = function() {
  Schemas.CountryShipping.create(sampleShippingData)
    .then(() => db.disconnect());
};

insertSampleShippingData();

// const removeSampleProducts = function() {
//   Schemas.Product.remove({})
//     .then(() => db.disconnect());
// };

// removeSampleProducts();

// const removeSampleShippingData = function() {
//   Schemas.CountryShipping.remove({})
//     .then(() => db.disconnect());
// };

// removeSampleShippingData();